PathPlanning/ModelPredictiveTrajectoryGenerator/model_predictive_trajectory_generator.py

Mistake in computation of the Jacobian.

Jacobian computation in  model_predictive_trajectory_generator.py

---

PathPlanning/QuinticPolynomialsPlanner/quintic_polynomials_planner.py

per my "issue", I have submitted a merge request with the work we discussed.

[feature request]: jerk limiting in quintic planner

---

PathPlanning/BezierPath/bezier_path.py

#70
Add comments + support for n point bezier curve
\+ add documentation for bezier curve
\+ add computation of derivatives and curvature
\+ display tangent, normal and radius of curvature
I removed import of the math module as everything can be done with numpy.

Add comments + support for n point bezier curve

---

PathTracking/stanley_controller/stanley_controller.py

This PR adds comments + docstrings to stanley control. I also renamed some variables to be more meaningful, remove the `import math` in favor of `import numpy`.

Add documentation to stanley control

---

PathPlanning/ClosedLoopRRTStar/closed_loop_rrt_star_car.py
PathPlanning/ClosedLoopRRTStar/unicycle_model.py
PathPlanning/DubinsPath/dubins_path_planning.py
PathPlanning/LQRRRTStar/lqr_rrt_star.py
PathPlanning/ModelPredictiveTrajectoryGenerator/motion_model.py
PathPlanning/RRTDubins/dubins_path_planning.py
PathPlanning/RRTDubins/rrt_dubins.py
PathPlanning/RRTStarDubins/dubins_path_planning.py
PathPlanning/RRTStarDubins/rrt_star_dubins.py
PathPlanning/RRTStarReedsShepp/rrt_star_reeds_shepp.py
PathPlanning/ReedsSheppPath/reeds_shepp_path_planning.py
PathTracking/lqr_speed_steer_control/lqr_speed_steer_control.py
PathTracking/lqr_steer_control/lqr_steer_control.py
SLAM/EKFSLAM/ekf_slam.py
SLAM/FastSLAM1/fast_slam1.py
SLAM/FastSLAM2/fast_slam2.py
SLAM/GraphBasedSLAM/graph_based_slam.py

Update the `pi_2_pi` function from two while implementation to a modulo.
Initial code: 
```python
while(angle > math.pi):
angle = angle - 2.0 * math.pi
while(angle < -math.pi):
angle = angle + 2.0 * math.pi
return angle
```
New implementation:
```python
return (angle + math.pi) % (2*math.pi) - math.pi
```

Update the pi_2_pi function to a use of a modulo instead of two while.

---

SLAM/KF_basics_part_1.ipynb

Basic math, examples and concepts on Kalman filter contribution.

Kalman filter basics documentation - Part 1

---

RoboticArm/NLinkArm.py
RoboticArm/n_link_arm_ik.py

I'll work on a program to show motion planning in joint space next!

Inverse kinematics for n-link arm

---

PathTracking/move_to_pose/move_to_pose.py

Also, Line 29 is difficult to understand. Could it be written as "Beta is the angle between the vector connecting robot's position to goals position and goal's orientation"? Please let me know if it gives the wrong idea.

Fix small doc string typo

---

docs/index.rst

Tiny PR that adds a link to the github repo in the documentation

Add link to github repo

---

docs/modules/arm_navigation.rst

- added arm navigation with obstacle avoidance to html doc

Update doc for arm navigation

---

PathTracking/model_predictive_speed_and_steer_control/model_predictive_speed_and_steer_control.py
PathTracking/model_predictive_speed_and_steer_control/notebook.ipynb

In linear discrete model of C matrix, there should be a negative sign on the last item in the vector. In the code, it also misses. However, this missing does not affect the performance.

small bugs on linear discrete model of MPC

---

SLAM/EKFSLAM/ekf_slam.py
SLAM/iterative_closest_point/iterative_closest_point.py

I've completed the following:
- iterative closest point
- EKF slam

Doing the np.matrix -> np.array conversion (#115)

---

SLAM/GraphBasedSLAM/graph_based_slam.py

Hi Atsushi,
I change two things in two commits, thanks your time to review them.
**1. Observation not matching**
I deleted the duplicated initial pose node.  It will give you￼ perfect fit when you use zero Qsim and Rsim and also better fit using normal noise.
**2. Virtual measurement angle error issue**
. Since your observation here didn't measure the landmark's heading (consider it as a point), so your virtual measurement between poses should not have any heading information. I simply changed the angle error term and Jacobian row 3 to 0.

Graph SLAM duplicated pose 0 and virtual measurement angle error issue

---

README.md

Thank you for your creating this OSS.
With README.md, I fixed from `Path tracking` to `Path Tracking`

Fix small string typo with README.md

---

ArmNavigation/arm_obstacle_navigation/arm_obstacle_navigation_2.py

Most of the code comes from the great original simulation.
In this version, both the work space and joint space visualization are
done in the same figure, which provides a better understanding of the
simulation.
Obstacles have been made more tricky in the joint space.
Added facility to stop the simulatino by pressing 'q'.
Added some comments.

Added modified version of the arm obstacle avoidance simulation.

---

PathPlanning/Eta3SplinePath/eta3_spline_path.py
PathPlanning/Eta3SplineTrajectory/eta3_spline_trajectory.py

Hey @AtsushiSakai, I did this work awhile back and thought that it might make a good addition to your repo.  I referenced the technical writeup in the comment section, but I will include here again for your review https://jwdinius.github.io/blog/2018/eta3traj/.  I hope you find this useful.
P.s. I am still working on https://github.com/AtsushiSakai/PythonRobotics/issues/54 :)

polishing up continuous velocity profile overlay on path

---

SLAM/GraphBasedSLAM/graphSLAM_doc.ipynb

Hi @atsushi-sakai, this PR contains a notebook for a documentation of graphSLAM and code walk through with several examples.

documentation notebook for graphSLAM

---

PathPlanning/BatchInformedRRTStar/batch_informed_rrtstar.py

Hello, I'm studying robotics with your repository and I found small bug in code.

fix ellisoid calculation

---

PathPlanning/HybridAStar/a_star.py
PathPlanning/HybridAStar/car.py
PathPlanning/HybridAStar/hybrid_a_star.py

Hi, I translate your trailer_hybrid_a_star repo to python 2.7

hybrid a star

---

Mapping/kmeans_clustering/kmeans_clustering.py

kmeans_clusterimng.pyのupdate_clusters関数のcostの計算が恐らく間違っているので修正しました．
よろしくお願いします．

fixed miss code.

---

Mapping/kmeans_clustering/kmeans_clustering.py

I committed kmeans_clustering a while ago, but the setting of my git config was wrong and fixed it correctly. If you are ok, please merge again.

wrong setting of my git config

---

PathPlanning/RRTstar/rrt_star.py

I think It's not necessary to generate the path until the maxIter,  so I modified the program. Now it will stop once it finds a path to the goal.

Once find the path, stop RRT*

---

Localization/ensemble_kalman_filter/ensemble_kalman_filter.py

Hi.I inplemented **localization with Ensemble Falman Filter(EnKF)**.
the EnKF uses a set of particles as with the Particle Filter(PF) 
and makes the assumption that involved probability distributions are Gaussian.
When it is applicable, the EnKF is more efficient than the PF. 
Please advise me if you want this PR be merged.
Ref:
- Ensemble Kalman filtering
https://rmets.onlinelibrary.wiley.com/doi/10.1256/qj.05.135

add localization with ensemble kalman filter

---

PathPlanning/HybridAStar/hybrid_a_star.py

A little change but looks more reasonable.^_^
I patched the yaw=0  when expanding the current node to get neighbors.
[Before]
[After]

patch the yaw=0 direction while expanding

---

PathPlanning/RRT/rrt.py
PathPlanning/RRT/rrt_with_pathsmoothing.py
PathPlanning/RRTStar/rrt_star.py

fix last expansion collision detection

---

Localization/ensemble_kalman_filter/ensemble_kalman_filter.py
Localization/extended_kalman_filter/extended_kalman_filter.py
Localization/unscented_kalman_filter/unscented_kalman_filter.py
SLAM/EKFSLAM/ekf_slam.py
SLAM/FastSLAM1/fast_slam1.py
SLAM/FastSLAM2/fast_slam2.py

try to fix randn problem with covariance matrix #236

fix_randn_problem_with_covariance_matrix

---

PathPlanning/DynamicWindowApproach/dynamic_window_approach.py

I've tried to use the algorithm with a grid map that generated with LIDAR data but the algorithm was too slow due to the increased number of obstacles. I've vectorized the calculation and now it is fast to use with a high number of obstacles.

Optimize DWA obstacle cost calculation

---

SLAM/iterative_closest_point/iterative_closest_point.py

Vectorize nearest_neighbor_assosiation. 
It took avarage 0.02 seconds for 3000->3000 points.
```
-`                    goktug@Goktug
.o+`                   -------------
`ooo/                   OS: Arch Linux x86_64
`+oooo:                  Host: 23257R2 ThinkPad X230
`+oooooo:                 Kernel: 5.3.7-arch1-1-ARCH
-+oooooo+:                Uptime: 6 hours, 14 mins
`/:-:++oooo+:               Packages: 1961 (pacman)
`/++++/+++++++:              Shell: zsh 5.7.1
`/++++++++++++++:             Resolution: 1366x768
`/+++ooooooooooooo/`           WM: i3
./ooosssso++osssssso+`          Theme: Arc-Dark [GTK2/3]
.oossssso-````/ossssss+`         Icons: Xenlism-Wildfire-SaturDay [GTK2/3]
-osssssso.      :ssssssso.        Terminal: st
:osssssss/        osssso+++.       Terminal Font: Fira Code …

optimize nearest_neighbor_assosiation

---

environment.yml

Add pip and coverage dependency in environment.yml file
- fix warning in running `conda env create -f environment.yml`
- fix error in running `./runtests.sh`

fix environment dependencies

---

PathTracking/pure_pursuit/pure_pursuit.py

- Added new method to state class
- Removed global variable old_nearest_point_index
- Created a class States that store the results

:hammer: Refactored pure_pursuit.py

---

Localization/Kalmanfilter_basics.ipynb

Some subscripts on the text are different from the actual code. It possibly confuses beginners.

[Kalman Basics] Align some subscripts on the text to follow the code

---

PathPlanning/RRTStar/rrt_star.py

fix RRT rewire

---

Localization/extended_kalman_filter/extended_kalman_filter.py

Following to Eq. (3.51) in Probabilistic Robotic book, G is depends on u_t and \mu_{t-1}, so I think in this code, jacob_F is depend on previous state instead of current predict state

fix compute jacobian of F in ekf_estimation

---

PathPlanning/AStar/a_star.py
PathPlanning/BestFirstSearch/best_first_search.py
PathPlanning/BidirectionalAStar/bidirectional_a_star.py
PathPlanning/BreadthFirstSearch/breadth_first_search.py
PathPlanning/DepthFirstSearch/depth_first_search.py
PathPlanning/GreedyBestFirstSearch/greedy_best_first_search.py

Implement Greedy Best-First Search.

Greedy Best-First Search

---

PathPlanning/AStar/a_star.py
PathPlanning/BidirectionalBreadthFirstSearch/bidirectional_breadth_first_search.py

Implement Bidirectional Breadth-First Search algorithm.

Bidirectional Breadth-First Search

---

.github/workflows/Linux_CI.yml
.github/workflows/MacOS_CI.yml
.github/workflows/pythonpackage.yml
.travis.yml
README.md
appveyor.yml

Update official Python version to 3.8

---

SLAM/FastSLAM1/fast_slam1.py
SLAM/FastSLAM2/fast_slam2.py

fix inaccurate covariance calculation to add a new landmark in FastSLAM1,2

---

.travis.yml
Localization/ensemble_kalman_filter/ensemble_kalman_filter.py
Localization/histogram_filter/histogram_filter.py
Localization/particle_filter/particle_filter.py
Mapping/lidar_to_grid_map/lidar_to_grid_map.py
Mapping/rectangle_fitting/rectangle_fitting.py
Mapping/rectangle_fitting/simulator.py
PathPlanning/AStar/a_star.py
PathPlanning/BidirectionalAStar/bidirectional_a_star.py
PathPlanning/BidirectionalBreadthFirstSearch/bidirectional_breadth_first_search.py
PathPlanning/BreadthFirstSearch/breadth_first_search.py
PathPlanning/ClosedLoopRRTStar/pure_pursuit.py
PathPlanning/DepthFirstSearch/depth_first_search.py
PathPlanning/Dijkstra/dijkstra.py
PathPlanning/DubinsPath/dubins_path_planning.py
PathPlanning/DynamicWindowApproach/dynamic_window_approach.py
PathPlanning/GreedyBestFirstSearch/greedy_best_first_search.py
PathPlanning/GridBasedSweepCPP/grid_based_sweep_coverage_path_planner.py
PathPlanning/HybridAStar/a_star_heuristic.py
PathPlanning/HybridAStar/car.py
PathPlanning/HybridAStar/hybrid_a_star.py
PathPlanning/InformedRRTStar/informed_rrt_star.py
PathPlanning/ProbabilisticRoadMap/probabilistic_road_map.py
PathPlanning/QuinticPolynomialsPlanner/quintic_polynomials_planner.py
PathPlanning/VoronoiRoadMap/dijkstra_search.py
SLAM/GraphBasedSLAM/graph_based_slam.py

Using scipy.spatial.rotation matrix

---

PathPlanning/PotentialFieldPlanning/potential_field_planning.py

2 changes:
1.  Potential field cover both start and goal - previously potential field was only defined at a certain area around any obstacles. So if goal/start are outside the area, the potential field is undefined, leading to the planner not converging. This fix extends the potential filed to include the start and goal if they are outside the obstacles area.
2. Add simple oscillations detection with horizon of the last 3 previous poses.

Potential field - potential range and ocillations

---

.github/workflows/Linux_CI.yml
Bipedal/bipedal_planner/bipedal_planner.py
PathPlanning/CubicSpline/cubic_spline_planner.py

improve test coverage

---

SLAM/EKFSLAM/ekf_slam.py
runtests.sh
tests/test_batch_informed_rrt_star.py
tests/test_closed_loop_rrt_star_car.py
tests/test_dubins_path_planning.py
tests/test_lqr_rrt_star.py
tests/test_n_joint_arm_to_point_control.py
tests/test_rrt.py

fix VisibleDeprecation Warning

---

.circleci/artifact_path
.circleci/config.yml
.github/workflows/Linux_CI.yml

Add .circleci/config.yml

---

.github/workflows/Linux_CI.yml

remove code cov check

---

PathPlanning/RRT/rrt.py
PathPlanning/RRTStar/rrt_star.py
tests/test_rrt_star.py

Fix  issues #382 and #383.
See the issues

Bug RRT* fix, issues #382 and #383

---

ArmNavigation/two_joint_arm_to_point_control/two_joint_arm_to_point_control.py

#409 
Fixed the bug where when you click outside the figure, it throws TypeError. Now it just ignores the outside clicks.

fixed TypeError

---

Mapping/rectangle_fitting/rectangle_fitting.py

Using vectorization to speed up computation

---

tests/test_rectangle_fitting.py

add test_rectangle_fitting.py

---

PathPlanning/ClosedLoopRRTStar/pure_pursuit.py

fix pure_pursuit sample in closed RRT

---

.circleci/config.yml
.github/workflows/Linux_CI.yml
.github/workflows/MacOS_CI.yml
README.md
appveyor.yml
docs/getting_started.rst
requirements.txt

fix #417 
bump python version to python 3.9.

bump python version to python 3.9.

---

.github/pull_request_template.md
ArmNavigation/two_joint_arm_to_point_control/two_joint_arm_to_point_control.py
PathPlanning/Eta3SplinePath/eta3_spline_path.py
PathPlanning/Eta3SplineTrajectory/eta3_spline_trajectory.py
README.md
requirements.txt
runtests.sh

fix #451
use pytest for test runner

use pytest for test runner

---

ArmNavigation/n_joint_arm_3d/NLinkArm3d.py

None
Improvement visualization on google colab.
This is very small PR.
[Test result on Google Colab notebook](https://colab.research.google.com/drive/1b4TMOeF3E5qI16eeC85qeUXhR0uwciHi?usp=sharing)

Add plot initialize for google colab visualization

---

.circleci/config.yml
.github/workflows/Linux_CI.yml
.github/workflows/MacOS_CI.yml
appveyor.yml

Remove workaround codes for CI

---

.github/workflows/Linux_CI.yml
.github/workflows/MacOS_CI.yml
PathPlanning/GridBasedSweepCPP/grid_based_sweep_coverage_path_planner.py
PathPlanning/StateLatticePlanner/state_lattice_planner.py
appveyor.yml
runtests.sh
tests/test_state_lattice_planner.py

Use pytest_xdist for unit-test speed up in CI

---

.github/workflows/codeql.yml
tests/test_lqr_speed_steer_control.py
tests/test_model_predictive_speed_and_steer_control.py
tests/test_move_to_pose.py
tests/test_n_joint_arm_to_point_control.py
tests/test_particle_filter.py
tests/test_potential_field_planning.py
tests/test_pure_pursuit.py
tests/test_quintic_polynomials_planner.py
tests/test_raycasting_grid_map.py
tests/test_rectangle_fitting.py
tests/test_reeds_shepp_path_planning.py
tests/test_rocket_powered_landing.py
tests/test_stanley_controller.py
tests/test_state_lattice_planner.py
tests/test_two_joint_arm_to_point_control.py
tests/test_unscented_kalman_filter.py
tests/test_visibility_road_map_planner.py
tests/test_voronoi_road_map_planner.py

add main script for missing tests

---

.github/workflows/Linux_CI.yml
.github/workflows/MacOS_CI.yml

Try to fix mypy CI

---

README.md
environment.yml
requirements.txt

Clean up README.md

---

Mapping/lidar_to_grid_map/lidar_to_grid_map.py
PathPlanning/SpiralSpanningTreeCPP/spiral_spanning_tree_coverage_path_planner.py
PathPlanning/WavefrontCPP/wavefront_coverage_path_planner.py
SLAM/EKFSLAM/ekf_slam.py
SLAM/GraphBasedSLAM/graphslam/graph.py
SLAM/GraphBasedSLAM/graphslam/load.py
SLAM/GraphBasedSLAM/graphslam/pose/se2.py
SLAM/GraphBasedSLAM/graphslam/util.py
requirements.txt

fix #476 
fix deprecation version for latest numpy

fix deprecation warning for latest numpy

---

PathPlanning/StateLatticePlanner/state_lattice_planner.py

fix state_lattice_planner.py coordinate conversion

---

.github/workflows/codeql.yml

add workaround for dependabot related issue

---

PathPlanning/DStarLite/DStarLite.py
PathPlanning/DStarLite/d_star_lite.py
README.md
tests/test_d_star_lite.py

- [Done] This project only accept codes for python 3.9 or higher.
- [Done] If you add a new algorithm sample code, please add a unit test file under `test` dir.
This sample test code might help you : https://github.com/AtsushiSakai/PythonRobotics/blob/master/tests/test_a_star.py
- [N/A] If you fix a bug of existing code please add a test function in the test code to show the issue was solved.
- [Done] Please fix all issues on CI (All CI should be green), before code review.
Add D* Lite algorithm to the repository. It contains the live version of the algorithm, which detects obstacles as it moves, and re-routes. The creating/detection of the obstacles can be random or specified by stating at which time step the obstacle is to be detected. The function names used and the structure of the …

Add D* Lite.

---

PathPlanning/VoronoiRoadMap/dijkstra_search.py

fix #514
Fixes the dijkstra_search where the hypotenuse check was incorrect and returning a false 'same node'

fix dijkstra hypot check bug

---

PathPlanning/DubinsPath/dubins_path_planning.py
PathPlanning/RRTDubins/rrt_dubins.py
PathPlanning/RRTStarDubins/rrt_star_dubins.py
tests/test_dubins_path_planning.py

fix dubins path length bug and clean up codes.

---

PathPlanning/ReedsSheppPath/reeds_shepp_path_planning.py
tests/test_reeds_shepp_path_planning.py

Fix reeds shepp path issue

---

PathPlanning/CubicSpline/cubic_spline_planner.py
PathTracking/rear_wheel_feedback/rear_wheel_feedback.py

typo
correct typo from intepolated to interpolated
correct typo from propotional to proportional

Correct typos

---

docs/modules/extended_kalman_filter_localization.rst

I modified some of the notations so that it will be less confusing (I was confused reading it).
- It is better to specify of which the Jacobian matrix is, here it is the transition and measurement function `f` and `g` (writing it as `J_F` and `J_H` is misleading)
- It is better to use `Delta` so as not to confuse people with the `d` commonly used in derivative
- It is more correct to use `\partial` instead of `d` since it is more multivariate than it is not
- Fix minor errors like extra brackets

Modify notations

---

README.md
requirements.txt

clean up doc system

---

README.md
requirements.txt

clean up doc dir

---

Control/move_to_pose/move_to_pose.py
tests/test_move_to_pose.py

I implemented the robot's speed limitations (i.e., maximum linear speed and maximum angular speed). 
There was not any open issue. I just did a minor improvement by adding 10 lines of codes.

Add speed limitation of the robot

---

appveyor.yml

Try to fix appveyor CI

---

PathPlanning/ProbabilisticRoadMap/probabilistic_road_map.py
tests/test_probabilistic_road_map.py

Add rng provide function for PRM planner

---

docs/how_to_contribute_main.rst

add doc policy

---

docs/requirements.txt

add requirements.txt under docs dir.

---

PathPlanning/Eta3SplineTrajectory/eta3_spline_trajectory.py
PathTracking/lqr_speed_steer_control/lqr_speed_steer_control.py
PathTracking/lqr_steer_control/lqr_steer_control.py
PathTracking/model_predictive_speed_and_steer_control/model_predictive_speed_and_steer_control.py
PathTracking/stanley_controller/stanley_controller.py
tests/test_model_predictive_speed_and_steer_control.py

1. Fix ModuleNotFoundError when executing test in the tests folder
2. Improve model_predictive_speed_and_steer_control.py:
- Fix typo
- Fix cvxpy warning about deprecated matrix multiplication syntax
- Fix missing conftest module in test file

Fix ModuleNotFoundError when executing test in the tests folder and little improve MPC controller

---

AerialNavigation/rocket_powered_landing/rocket_powered_landing.py
PathPlanning/ProbabilisticRoadMap/probabilistic_road_map.py
tests/test_model_predictive_speed_and_steer_control.py
tests/test_probabilistic_road_map.py
tests/test_rocket_powered_landing.py

enable MPC test

---

.github/workflows/Linux_CI.yml
.github/workflows/MacOS_CI.yml
PathPlanning/DStarLite/d_star_lite.py
requirements.txt
tests/test_mypy_type_check.py

add mypy unit test

---

docs/modules/control/move_to_a_pose_control/move_to_a_pose_control.rst

Lots of contents were not displayed correctly. I put some empty lines and :math: labels to fixed it.
Documentation of move to pose algorithm #596

Fix format to show contents properly

---

docs/modules/control/move_to_a_pose_control/move_to_a_pose_control.rst
docs/modules/path_planning/quintic_polynomials_planner/quintic_polynomials_planner.rst

fix duplicated math lables

---

.circleci/artifact_path
.circleci/config.yml
.github/workflows/circle_artifacts.yml
.github/workflows/circleci-artifacts-redirector.yml

fix doc artifact link in CI

---

.github/workflows/gh-pages.yml

add gh-pages action

---

docs/_templates/layout.html

enhance_github pages doc

---

.github/pull_request_template.md
README.md
docs/conf.py
docs/how_to_contribute_main.rst
users_comments.md

remove old doc links

---

Localization/ensemble_kalman_filter/ensemble_kalman_filter.py
Localization/extended_kalman_filter/extended_kalman_filter.py
Localization/particle_filter/particle_filter.py
Localization/unscented_kalman_filter/unscented_kalman_filter.py
Mapping/rectangle_fitting/rectangle_fitting.py
Mapping/rectangle_fitting/simulator.py
PathPlanning/GridBasedSweepCPP/grid_based_sweep_coverage_path_planner.py
PathPlanning/HybridAStar/car.py
PathPlanning/InformedRRTStar/informed_rrt_star.py
SLAM/GraphBasedSLAM/graph_based_slam.py

Using utility rot_mat_2d

---

SLAM/GraphBasedSLAM/graphslam/util.py

This fixes a bug in `upper_triangular_matrix_to_full_matrix`; for more info, see https://github.com/JeffLIrion/python-graphslam/pull/29 and the issue that it resolved (https://github.com/JeffLIrion/python-graphslam/issues/28).

Fix `upper_triangular_matrix_to_full_matrix`

---

README.md

Remove pandas dependency

---

Mapping/rectangle_fitting/simulator.py

fix mypy ci

---

.github/workflows/gh-pages.yml

Fix gh-pages issue on master

---

PathPlanning/RRT/rrt_with_sobol_sampler.py

Undefined name: import sys for line 188

---

Mapping/rectangle_fitting/rectangle_fitting.py
PathPlanning/AStar/a_star.py
PathPlanning/BidirectionalAStar/bidirectional_a_star.py
PathPlanning/BidirectionalBreadthFirstSearch/bidirectional_breadth_first_search.py
PathPlanning/BreadthFirstSearch/breadth_first_search.py
PathPlanning/DepthFirstSearch/depth_first_search.py
PathPlanning/Dijkstra/dijkstra.py
PathPlanning/GreedyBestFirstSearch/greedy_best_first_search.py
PathPlanning/HybridAStar/dynamic_programming_heuristic.py
tests/test_grid_map_lib.py

This replaces the loop conditions `while 1:` with more idiomatic `while True:`, and fixes a couple of missing imports.

Update loop conditions to be more idiomatic; fix missing imports

---

PathPlanning/AStar/a_star_searching_from_two_side.py

Minor - correct grammatical error :)
__This corrects a minor grammatical error in the print message, which is shown when the path search is successful.__

Change 'Path is find!' to 'Path found!'

---

PathPlanning/DStarLite/d_star_lite.py

Change-Id: I6e421a1c2524a3d8f8875121a1a6d2ed832c3150
I've noticed that the current Implementation uses lists. By replacing them with numpy arrays and using built in numpy functions such as any, I reduced the calculation time of d_star_lite. The other thing that I've noticed, once after initializing class, if the user wants to add new spoofed objects and calculate a new path, it was not using the prior information that is generated. So I modified the initialization process a bit to use the prior information.

Utilize numpy to reduce calculation time

---

PathPlanning/InformedRRTStar/informed_rrt_star.py

clean up informed_rrt_star.py

---

Mapping/rectangle_fitting/rectangle_fitting.py
docs/modules/mapping/rectangle_fitting/rectangle_fitting_main.rst
docs/modules/slam/FastSLAM1/FastSLAM1_main.rst

Enhance rectangle fitting docs

---

requirements/requirements.txt

upgrade scipy and cvxpy

---

docs/how_to_contribute_main.rst

The PR updates the location of the code style test script. In PR #787 it was moved from `tests/test_diff_codestyle.py` to `tests/test_codestyle.py`. The PR simply updates the docs with the correct location.

docs: update the code style test script

---

.github/workflows/gh-pages.yml

Fix gh-pages error

---

ArmNavigation/arm_obstacle_navigation/arm_obstacle_navigation_2.py

Inappropriate Logical Expression
While triaging your project, our bug fixing tool generated the following message(s)-
In file: [arm_obstacle_navigation_2.py](https://github.com/demisto/content/blob/master/Packs/opswat-metadefender/Integrations/OPSWATMetadefenderV2/OPSWATMetadefenderV2.py#L217), the comparison of Collection length creates a logical short circuit. iCR suggested that the Collection length comparison should be done without creating a logical short circuit.
The condition **len(route) >= 0** will always evaluate to true because the length can never be negative. If you intend to check whether route is not an empty collection, you can directly check for that:
```
if route:
animate(grid, arm, route)
```
This section is only relevant if your project requires contributors to sign a …

Fixed Inappropriate Logical Expression

---

PathPlanning/DStar/dstar.py

Fix code scan alert

---

docs/doc_requirements.txt

Update doc_requirements.txt versions

---

Control/move_to_pose/move_to_pose.py

The PathFinderController class in Control/move_to_pose/move_to_pose.py, line 77 Kp_beta, should be self. Not the controller.

fix::Control PathFinderController bug

---

Localization/particle_filter/particle_filter.py

Fix covariance dimension

---

ArmNavigation/n_joint_arm_3d/NLinkArm3d.py

fix plot issue in random_inverse_kinematics.py

---

SLAM/FastSLAM1/fast_slam1.py
SLAM/FastSLAM2/fast_slam2.py

clean up fast slam codes

---

README.md

Nothing
fix typo in README.md
Before:

fix(README.md): typo in reeds-shepp path

---

docs/modules/path_planning/path_planning_main.rst

Add catmull_rom_spline doc

---

docs/modules/0_getting_started/2_how_to_run_sample_codes_main.rst

update getting started

---

docs/modules/3_mapping/distance_map/distance_map_main.rst

Fix the path of autofunction in the distance_map document.

fix: DistanceMap doc autofunction

---

docs/modules/1_introduction/2_python_for_robotics/python_for_robotics_main.rst

update introduction doc

---

README.md

update contribution link in README.md to fix invalid link

---

docs/modules/1_introduction/1_definition_of_robotics/definition_of_robotics_main.rst

update robotics definition document to enhance references and clarity

---

docs/modules/12_appendix/appendix_main.rst
docs/modules/12_appendix/external_sensors_main.rst
docs/modules/12_appendix/internal_sensors_main.rst

add internal sensors documentation to appendix and create new internal sensors overview

---

PathPlanning/TimeBasedPathPlanning/SpaceTimeAStar.py

N/A
Fixed a tiny typo in the comments of the Space-time A* algorithm code.  On line 6 "respescting" --> "respecting"
N/A
N/A
N/A
N/A

bug: fix typo on line 6 of SpaceTimeAStar.py
