AtsushiSakai/PythonRobotics

Localization/particle_filter/particle_filter.py
Within the first ten or so iterations, taking the square root of an extremely small negative number was attempted, resulting in a math domain error.
=> Fixed occasional math domain error

Mapping/raycasting_grid_map/raycasting_grid_map.py, PathPlanning/PotentialFieldPlanning/potential_field_planning.py
The floor function in Python 2 returns a float, leading to an index error in some cases. Converted indexes explicitly to ints.
=> Fixed issue with float index for Python 2

PathPlanning/FrenetOptimalTrajectory/frenet_optimal_trajectory.py
The previous implementation of the frenet optimal planner used a finite difference of acceleration for the jerk calculation.  I've updated the planner to use analytical jerk calculations using the time derivatives of polynomials.
=> analytic jerk calculation in frenet_optimal_planner.py

PathPlanning/Eta3SplinePath/eta3_spline_path.py
I found an interesting path generator that is geometrically continuous up to order 1 (the derivative is guaranteed continuous).  The reference is [here](https://ieeexplore.ieee.org/document/4339545).  I was able to code up the algorithm and recreate the test case presented.  I thought that you might like to add it to your repo.
=> Add \eta^3 spline path to PathPlanning

PathTracking/lqr_speed_steer_control/lqr_speed_steer_control.py, PathTracking/lqr_steer_control/lqr_steer_control.py, PathTracking/model_predictive_speed_and_steer_control/model_predictive_speed_and_steer_control.py, PathTracking/rear_wheel_feedback/rear_wheel_feedback.py
Followup of #83.
This PR is calling `math.sqrt` once in the `calc_nearest_index` function instead of `len(points)` times. 
Note: In `model_predictive_speed_and_steer_control.py` replaced `min_d`  by `mind`
=> Optimize calc_nearest_index

PathPlanning/Eta3SplinePath/eta3_spline_path.py, environment.yml
This PR addresses the feature request I just created.  Users who prefer to use conda can setup their environments by navigating to the root of the PythonRobotics repo and typing: 
```
conda env create -f environment.yml
```
Then, to use the newly created `python_robotics` environment, they can type (from any directory):
```
source activate python_robotics
```
Also included in this PR (by mistake, but I was going to commit it anyways), is logic to compute the segment length in the `eta3_spline_path.py` code that was recently added.
=> add environment.yml to setup conda environment

PathPlanning/RRTstar/rrt_star.py
Please check the [paper](https://core.ac.uk/download/pdf/18173530.pdf), 'Steer()' function in **Algorithm 6** is $steer(x, y) = argmin_{z \in B_{x, \eta}} \Vert z-y \Vert$ and x can be within that ball. Also the cost and parent will be determined by following procedures.
=> fixed steer() in RRTstar

PathTracking/pure_pursuit/pure_pursuit.py
I suppose this should be `cy` not `cx`.
I found it because this module didn't work correctly when the path was horizontal.
=> Fixed a bug of calculating parameters in pure pursuit module

SLAM/EKFSLAM/ekf_slam.py
When I run this script, an error occured.
```
$python3 ekf_slam.py
ekf_slam.py start!!
New LM
Traceback (most recent call last):
File "ekf_slam.py", line 266, in <module>
main()
File "ekf_slam.py", line 234, in main
xEst, PEst = ekf_slam(xEst, PEst, ud, z)
File "ekf_slam.py", line 54, in ekf_slam
xEst = xEst + (K @ y)
TypeError: ufunc 'matmul' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
I found that `xEst[2]`(l. 173) is a 1d-array, so I modified it to be scalar.
=> fixed bug of ekf_slam.py

PathTracking/pure_pursuit/pure_pursuit.py
Two changes made:
- calculate distance between car and all points on path only once, then recalculate based on the old nearest point index and short range until the distance increases
- use rear axle instead of car center
=> Optimize PurePursuit, use right axle

PathPlanning/ProbabilisticRoadMap/probabilistic_road_map.py
When creating a simple square of obstacles, the sampled points are not inside of it, if it is centered around (0, 0)
=> Fixed the sampling function from PRM

PathPlanning/ProbabilisticRoadMap/probabilistic_road_map.py
Added a simple boolean variable to track the state of the algorithm and return something empty when no path is found.
Added and fixed (partially) the documentation
=> Code live lock when no path is found

PathPlanning/DynamicWindowApproach/dynamic_window_approach.py
Signed-off-by: KoenHan <sliver1998324@gmail.com>
I changed it as follows:
- Changed the computation method of to_goal_cost.
Implemented calc_to_goal_cost function more closely to the method proposed in the paper of DWA.
=> DWA cost function toward goal

README.md
While going through the documentation I noticed that the link the latest version of CVXPY was broken.
=> cvxpy link fixed

AerialNavigation/drone_3d_trajectory_following/drone_3d_trajectory_following.py
thrust variable is currently a 1D numpy array so the matmul function throws an error when executed, converting thrust to a scalar before the matmul operation solves the issue.
=> convert 1D array to scalar for np.matmul operation

PathPlanning/DynamicWindowApproach/dynamic_window_approach.py, tests/test_dynamic_window_approach.py
Add a collision check for the rectangular robots.
=> DWA Rectangle Robot Type

Localization/particle_filter/particle_filter.py
- changed resampling function so that it chooses random number once for the starting point.
- condition check is moved from the inside of the resampling function
to the outside of the function, this way the purpose of the
function is much clear. Instead "resampling" every iteration,
resample if the condition holds.
=> change PF resampling function to match with the book

PathPlanning/DynamicWindowApproach/dynamic_window_approach.py
After adding the rectangle obstacle calculation, I've tested the algorithm more to try different settings
and I've seen that sometimes robot hits obstacles, specifically during turns. I've realized, the yaw angle should be positive instead of negative while rotating the obstacles because of the dot order (`a @ rot` instead of `rot @ a`). After the change, the robot stops before hitting the obstacles.
=> DWA Fix wrong rotation direction

PathPlanning/InformedRRTStar/informed_rrt_star.py
The previous method only worked because the step that checked collision
from a point of the line to obstacles was the same as the minimum
obstacle radius. If the obstacle radius is very small a great amount of
steps would be required.
Thus It's better to check the distance from the segment to the obstacles
directly and compare with obstacle radius
Now there is no need to have two check functions.
Example with same parameters as the issue:
=>  fix #233 improve check segment intersection with obstacle

PathPlanning/InformedRRTStar/informed_rrt_star.py
Remove pathLen in informed RRT* and instead with cBest updating.
=> Fix #247 add cBest update in Informed RRT*

SLAM/EKFSLAM/ekf_slam.ipynb, SLAM/EKFSLAM/ekf_slam.py
I believe the partial derivative of an observation with respect to the angle should be equal to `-1`, yet in the code it's currently `-1/q`.
Here is a source I could find on the topic: 
http://ais.informatik.uni-freiburg.de/teaching/ws12/mapping/pdf/slam04-ekf-slam.pdf, Slide 33
Would greatly appreciate it if someone would take a second look!
=> EKF-SLAM: Fix jacobian of observation

SLAM/EKFSLAM/ekf_slam.ipynb, SLAM/EKFSLAM/ekf_slam.py
Fixes the computation of the predicted covariances after a motion command, by changing elementwise multiplication to matrix multiplication.
=> EKF-SLAM: Fix prediction step of motion

PathTracking/stanley_controller/stanley_controller.py
Used:
- np.hypot to replace `np.sqrt(x**2 + y**2)`
- np.argmin to find location of a minimum in a numpy array
=> Simplified calc_target_index function in stanley_controller.py

PathPlanning/AStar/a_star.py
There is a typo on line 54 in the planning method docstring.
=> Fixed typo in planning method docstring

PathTracking/rear_wheel_feedback/rear_wheel_feedback.py
- Utilize scipy module to reduce internal dependency (cubic spline)
- Reduce high context parameters in rear_wheel_feedback_control function
Other proposal (not implemented): 
- Speed profile is disabled; could direction switching be decided at line 143? this would be closer to real-world implementation.
- pi_2_pi could also be replaced to numpy unwrap; though I think it is not so effective on readability.
=> [Proposal] Reduce internal dependancy

PathPlanning/AStar/a_star.py, PathPlanning/BidirectionalAStar/bidir_a_star.py, PathPlanning/BidirectionalAStar/bidirectional_a_star.py
Implement Bidirectional A* algorithm. (two A* searching for the last node added to the other's closed set).
=> Bidirectional A*

PathPlanning/HybridAStar/hybrid_a_star.py, tests/test_hybrid_a_star.py
=> Fix Hybrid A*

Bipedal/bipedal_planner/bipedal_planner.py, PathPlanning/ReedsSheppPath/reeds_shepp_path_planning.py, tests/test_bipedal_planner.py
=> fix bipedal_planner and add its test

.github/codeql/codeql-config.yml, .github/workflows/codeql.yml
Hi, I'm a PM on the GitHub security team. This repository is eligible to try the new [GitHub Advanced Security code scanning](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning) beta.
Code scanning runs a static analysis tool called CodeQL which scans your code at build time to find any potential security issues. We've tuned the set of queries to be only the most severe, most precise issues. We'll show alerts in the security tab, and we'll show alerts for any net new vulnerabilities on pull requests as well. We've tried to make this super developer friendly, but we'd love your feedback as we work through the beta. 
If you're interested in trying it out, you can merge this pull request to set up the Actions workflow.
=> Add CodeQL security scanning

.github/workflows/circleci-artifacts-redirector.yml, PathPlanning/HybridAStar/dynamic_programming_heuristic.py, PathPlanning/HybridAStar/hybrid_a_star.py
=> refactor hybrid_a_star codes and clean up heuristic function names 

PathPlanning/RRTStar/rrt_star.py, tests/test_rrt_star.py
since `last_index` is 0 when there is no obstacle, the planning will return no path found. Checking for `last_index` being `None` will resolve this issue.
=> support no obstacle in RRT*

PathPlanning/AStar/A_Star_searching_from_two_side.py, tests/test_a_star_searching_two_side.py
1. rewrite A star algorithm, improved efficiency by searching the path from two side simultaneously (i.e. from start to goal + from goal to start)
2. generate obstacles map randomly, the number of obstacle is adjustable
Find a path:
No path to the goal, indicate the boundary confine robot or goal:
=> New A star algorithm pr

ArmNavigation/two_joint_arm_to_point_control/two_joint_arm_to_point_control.py
two joint arm point control example will no longer fail if target point is out of reach
=> robustified 2 joint arm example

Localization/ensemble_kalman_filter/ensemble_kalman_filter.py, Localization/extended_kalman_filter/extended_kalman_filter.py, Localization/particle_filter/particle_filter.py, Localization/unscented_kalman_filter/unscented_kalman_filter.py
This change suggests a more intuitive way of `plot_covariance_ellipse()` in `extended_kalman_filter.py` and `unscented_kalman_filter.py`. (This change doesn't affect the result.)
In `plot_covariance_ellipse()`, `np.linalg.eig(Pxy)` returns `eigval` and `eigvec` like below. 
```
eigval = [ l1, l2 ]
eigvec = [
[v1_x, v2_x],
[v1_y, v2_y]
]
```
So, I think it would be more  plausible if the `angle` of the ellipse and the `rot` matrix are calculated by
```
angle = atan2(v1_y, v1_x)
rot = [
[cos(angle), -sin(angle)],
[sin(angle),  cos(angle)]
]
```
The result is the same between before and after.
```
angle = math.atan2(eigvec[bigind, 1], eigvec[bigind, 0])
rot = np.array([[math.cos(angle), math.sin(angle)],
[-math.sin(angle), math.cos(angle)]]))
```
&#8595;
```
angle_ = math.atan2(eigvec[1, …
```
=> More intuitive way of plot_covariance_ellipse()

SLAM/iterative_closest_point/iterative_closest_point.py
fix #446
Fixes case of negative ```dError``` in ICP algorithm.
Implementation:
When ```dError``` is negative (error is rising) exits iteration loop with values of previous iterations with lower error. 
The first iteration is guaranteed by defining ```dError``` and ```preError``` as np.inf before the loop.
=> fix ICP negative dError. Issue #446

PathPlanning/RRT/rrt.py, PathPlanning/RRT/rrt_with_sobol_sampler.py, PathPlanning/RRT/sobol/__init__.py, PathPlanning/RRT/sobol/sobol.py, tests/test_rrt_with_sobol_sampler.py
This pull request implements a low discrepancy sequence for the generation of sample points in the RRT method.
Low discrepancy sampler are preferred over uniform random distribution because they provide a more evenly distributed sequence of points. 
The [Sobol sequence](https://en.wikipedia.org/wiki/Sobol_sequence) was implemented using the code with MIT licence available [here](http://people.sc.fsu.edu/~jburkardt/py_src/sobol/sobol.html). 
Sorry if I did not create an Issue before, but the pull request was very straight forward. If it is necessary, I can create the issue.
=> Sobol sampler implemented

environment.yml
I ran into #342 where I cannot just create a new conda environment using the existing `environment.yml` file.
See #342.
1. I added a channel to the yml file so that conda knows where to look for packages like `cvxpy`.
2. Since [requirements](https://pythonrobotics.readthedocs.io/en/latest/getting_started.html#requirements) needs Python to be 3.9 and up. I specified it in the yml file as well.
None.
=> Fix: cvxpy cannot be installed

PathPlanning/ReedsSheppPath/reeds_shepp_path_planning.py
…mpared. Optimal path may be discarded.
1. Function 'mod' in numpy library behaves differently from 'fmod' in c++ and it should be treated specially in the implementation of the function 'mod2pi'.
2. In the implementation of function 'set_path', the basis of path length comparison should be the sum of the absolute value of its segment length, otherwise the optimal path may be lost.
E.g. start point (0, 0, 0), end point defined as follows:
t, u, w = -math.pi / 6., math.pi / 2., math.pi / 3.
end_x = math.sin(w - u + t) + 2. * math.sin(u - t) + 2. * math.sin(t)
end_y = -math.cos(w - u + t) + 2. * math.cos(u - t) - 2. * math.cos(t) + 1.
end_yaw = w - u + t
and the optimal path is 'L_t' + 'R_u' + 'L_w' which gives minimum path length math.pi(i.e. 3.14) while the original program presents a …
=> Fix the problem that the optimal path may be discarded.

SLAM/iterative_closest_point/iterative_closest_point.py, tests/test_iterative_closest_point.py
fix #464
Adds an implementation of code for ICP to work both for 2d and 3d point clouds.
Make functions `icp_matching()` and `update_homogeneous_matrix()` flexible. Depending on the `current_points.shape[0]` function `svd_motion_estimation()` automatically returns the correct size for `Rt`, `Tt`. Then, in `update_homogeneous_matrix()` depending on their size matrix `H` is formed to be 3x3 or 4x4. 
Test for 3d point cloud is provided. Made the same manner as tests for 2d point cloud.
=> Add ICP support for 3d point clouds

PathPlanning/ClosedLoopRRTStar/__init__.py, PathPlanning/ClosedLoopRRTStar/closed_loop_rrt_star_car.py, PathPlanning/GridBasedSweepCPP/__init__.py, PathPlanning/GridBasedSweepCPP/grid_based_sweep_coverage_path_planner.py
fix #515
changed import Module path.
all the other codes has sys.path.append code in the main python code except
GridBasedSweepCPP and ClosedLoopRRTStart has in __init__.py which makes "No module error"
=> Fix No module error in GridBasedSweepCPP and ClosedLoopRRTStart

PathPlanning/RRT/rrt.py
Thanks for creating PythonRobotics!
Just a tiny addition...
Limits the available play area (add walls) in the RRT sample.
=> Limit play area in RRT

README.md
The gif link is broken now. I think this is the right URL.
no
doc only.
=> Fix a broken gif link in the "Lidar to grid map"

docs/modules/localization/extended_kalman_filter_localization_files/extended_kalman_filter_localization.rst
Reference issue
typo
What does this implement/fix?
Update motion function in localization/EKF documentation. Add missing delta t.
=> Fix typo: correction for missing 'delta t' in EKF documentation

PathPlanning/ClosedLoopRRTStar/closed_loop_rrt_star_car.py, PathPlanning/LQRRRTStar/lqr_rrt_star.py, PathPlanning/RRT/rrt.py, PathPlanning/RRT/rrt_with_sobol_sampler.py, PathPlanning/RRTDubins/rrt_dubins.py, PathPlanning/RRTStar/rrt_star.py, PathPlanning/RRTStarDubins/rrt_star_dubins.py, PathPlanning/RRTStarReedsShepp/rrt_star_reeds_shepp.py, tests/test_rrt_star.py, tests/test_rrt_star_reeds_shepp.py
* update `__init__` and `check_collision` in RRT class to include a robot radius
* during animation, if a robot radius is given then it is drawn
This simply adds an optional robot radius feature for the RRT/RRTStar path planners. 
Examples updated to highlight feature.
=> Add optional robot radius to RRT/RRTStar path planners

.circleci/config.yml, .github/workflows/Linux_CI.yml, .github/workflows/MacOS_CI.yml, README.md, appveyor.yml, docs/getting_started_main.rst, requirements/environment.yml
To fix #557
Bump python-support to 3.10.
=> try to use python3.10

PathPlanning/DStar/dstar.py
https://github.com/AtsushiSakai/PythonRobotics/issues/657
- An error is found in "PathPlanning/DStar/dstar.py", line 163
- Before added into open_list, the end node's state should be set as "open". Otherwise, the end node's state is remained to be "new" and it's member "h" will be rewritten by it's neighbor nodes later since "new" means this node hasn't been processed.
- I create this pull request to modify this error. You can accept it or fix the error by yourself since there is only one line of codes being changed.
=> modify the error of end node's state in DStar

Mapping/grid_map_lib/grid_map_lib.py, tests/test_grid_map_lib.py
fix error: 'numpy.ndarray' object has no attribute 'append'
When running `grid_based_sweep_coverage_path_planner.py` and giving `ox` and `oy` without `ox[0] == ox[-1]`, you will get `fix error: 'numpy.ndarray' object has no attribute 'append'`
=> fix error: 'numpy.ndarray' object has no attribute 'append'

PathPlanning/FrenetOptimalTrajectory/frenet_optimal_trajectory.py
#755
The robot didn't reach the target velocity when running frenet_optimal_trajectory.py.
To fix this, I changed the constraints for determining polynomials that generate longitudinal trajectories according to paper.
Expressly, I set the initial acceleration to the current acceleration.
=> Fix the start state to use the current accel in frent planner(#755)

Bipedal/bipedal_planner/bipedal_planner.py
The Bipedal Planner code won't show the drawing. The reason is that since Matplotlib V3.4.0, Axes3D automatically adding itself to Figure is deprecated. The fix here is to add the axes3d to figure manually.
Reference reading: https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.4.0.html
=> add axes3d to figure

ArmNavigation/two_joint_arm_to_point_control/two_joint_arm_to_point_control.py, Bipedal/bipedal_planner/bipedal_planner.py, PathPlanning/HybridAStar/dynamic_programming_heuristic.py, PathPlanning/InformedRRTStar/informed_rrt_star.py, PathPlanning/LQRPlanner/lqr_planner.py, PathPlanning/LQRRRTStar/lqr_rrt_star.py, PathPlanning/RRT/rrt_with_pathsmoothing.py, PathPlanning/ReedsSheppPath/reeds_shepp_path_planning.py
=> fix github scanning alerts

docs/conf.py, docs/getting_started_main.rst, requirements/requirements.txt, ruff.toml, tests/test_codestyle.py
=> using ruff instead of flake8

PathPlanning/RRTStar/rrt_star.py, PathPlanning/RRTStarReedsShepp/rrt_star_reeds_shepp.py, PathPlanning/ReedsSheppPath/reeds_shepp_path_planning.py, tests/test_rrt_star_reeds_shepp.py
fix #550 
rrt_star_reeds_shepp.py needs its own version of rewire(), which not only updates path_x , path_y, but also path_yaw when rewiring. 
Before this pull request, it uses the rewire() in rrt_star.py, which only cares about path_x, and path_y, thus issue #550 might occur.
The range of phi in rrt_star_reeds_shepp.py is changed from (0, 0.99\*math.pi) to (0.01\*math.pi, 0.99*math.pi) for the sake of speed.
Two tests are added into tests/test_rrt_star_reeds_shepp.py.
=> Fix the rewire() of rrt* path planning (#550) 

docs/conf.py, docs/doc_requirements.txt
Documentation lacked a copy button, so users could not quickly and easily copy code snippets. In the documentation, I added a copy code snippet feature. Now, Users can quickly and easily copy code snippets.
- pip install sphinx-copybutton
- In conf.py configuration file, add sphinx_copybutton
``` extensions = [  'sphinx_copybutton' ] ```
- Also, I added the sphinx-copybutton package to the **doc_requirements.txt** file
=> Add copy button in the documentation code snippets

docs/conf.py, docs/doc_requirements.txt
Many users prefer dark mode when they are reading documentation. Now, Users can choose their preferred color mode in documentation. By default, documentation mode will be in default mode, but the background will change when the user clicks the toggle button.
- pip install sphinx-rtd-dark-mode
- In conf.py configuration file, sphinx-rtd-dark-mode
``` extensions = [  'sphinx_rtd_dark_mode' ] ```
-  ``` html_theme = 'sphinx_rtd_light_theme' ```
- Also, I added the  sphinx-rtd-dark-mode package to the **doc_requirements.txt** file
=> Add dark mode feature in documentation

README.md
fix #858 
This pull request updates the broken links in the README.md file, ensuring that they match the appropriate documents on the documentation website.
In the _Extended Kalman Filter localization_ section, I added a line ```Ref:``` to maintain consistency with other sections.
=> Fix broken links in README.md for ipynb files

PathPlanning/GridBasedSweepCPP/grid_based_sweep_coverage_path_planner.py
This PR resolves #915 .
This PR just reverts the undesirable parameter change in `PathPlanning/GridBasedSweepCPP/grid_based_sweep_coverage_path_planner.py` summarised in #915 .
N/A
=> Revert a parameter in grid_based_sweep_coverage_path_planner to correct the planning results

PathPlanning/DStar/dstar.py
fix D* bug, not it can handle the changed map. #886
=> fix d_star, #886

SLAM/EKFSLAM/ekf_slam.py, docs/modules/slam/ekf_slam/ekf_slam_main.rst
=> Fix predict covariance

PathPlanning/InformedRRTStar/informed_rrt_star.py
Replacing the hard coded graph axis values with class variables
- Use self.min_rand, self.max_rand variable values in place of -2, 15
This replaces hard coded axis values of  -2, 15 with self.min_rand, self.max_rand class variables when drawing the graph
This makes the function re-usable for varying sized graphs, beyond the example case in the main function
=> PathPlanning/InformedRRTStar/informed_rrt_star.py: Fix hard coded graph axis

PathPlanning/RRT/rrt.py
The limits of the plots were fixed to (-2,15) which is the example random range. Adjusted to be rand_min, rand_max instead.
=> fixed hard-coded plot limits

ArmNavigation/rrt_star_seven_joint_arm_control/rrt_star_seven_joint_arm_control.py
When I run `ArmNavigation/rrt_star_seven_joint_arm_control/rrt_star_seven_joint_arm_control.py`, I get an error:
```Traceback (most recent call last):
File "/Users/tim/PythonRobotics/ArmNavigation/rrt_star_seven_joint_arm_control/rrt_star_seven_joint_arm_control.py", line 405, in <module>
main()
File "/Users/tim/PythonRobotics/ArmNavigation/rrt_star_seven_joint_arm_control/rrt_star_seven_joint_arm_control.py", line 384, in main
ax = rrt_star.draw_graph()
^^^^^^^^^^^^^^^^^^^^^
File "/Users/tim/PythonRobotics/ArmNavigation/rrt_star_seven_joint_arm_control/rrt_star_seven_joint_arm_control.py", line 268, in draw_graph
self.ax.axis([-1, 1, -1, 1])
File "/Users/tim/PythonRobotics/my_env/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 2114, in axis
raise TypeError(
TypeError: The …
```
=> Fixing ArmNavigation/rrt_star_seven_joint_arm_control/rrt_star_seven_joint_arm_control.py

ArmNavigation/arm_obstacle_navigation/arm_obstacle_navigation.py, ArmNavigation/arm_obstacle_navigation/arm_obstacle_navigation_2.py, requirements/requirements.txt
In def calc_heuristic_map(M, goal_node), the current code appears to calculate the cost from every node through 4 corners to the goal node and tries to find its min value. However, the cost from current node to 4 corners of the map is wrong. This commit is meant to fix the calculation of the cost.
=> fix: arm_obstacle_navigation calc_heuristic_map node through 4 corners error

PathPlanning/WavefrontCPP/wavefront_coverage_path_planner.py
None
This improves performance by transforming `calculated` into a set. As the only use is to check if a value is already calculated, keeping each value once is enough and it is faster to search in a set than a list.
This issue was found by [DyLin](https://github.com/AryazE/DyLin) via [auto-dylin](https://github.com/AryazE/auto-dylin).
=> Performance improvement

PathPlanning/HybridAStar/hybrid_a_star.py, PathPlanning/ReedsSheppPath/reeds_shepp_path_planning.py
None
Hybrid A* outputs path containing x, y, yaw, and direction.
But direction is not preserved correctly and its size is smaller than x, y, yaw.
size of x, y, yaw, direction -> 1235, 1235, 1235, 510
size of x, y, yaw, direction -> 1235, 1235, 1235, 1235
- Red line: Path.direction_list=True (forward)
- Blue line: Path.direction_list=False (backward)
`hybrid_a_star.py` throws module not found error because its dependency `reeds_shepp_path_planning.py` uses a module in root directory (`utils/angle.py`).
Therefore `sys.path` is also modified following other algorithms depending on `utils/angle.py`.
=> Fix: Hybrid A* direction is incorrect

PathPlanning/HybridAStar/car.py, PathPlanning/HybridAStar/hybrid_a_star.py
None
The vehicle goes out of the search grid when its angle is approximately pi, because  the yaw angle is not clipped correctly.
Example: set the start position reverse.
```diff
@@ -404,7 +404,7 @@ def main():
-    start = [10.0, 10.0, np.deg2rad(90.0)]
+    start = [10.0, 10.0, np.deg2rad(-90.0)]
goal = [50.0, 50.0, np.deg2rad(-90.0)]
```
Result:
```
Error(calc_index): -2959
Error(calc_index): -2030
Error(calc_index): -2959
Error(calc_index): -3019
...
```
`hybrid_a_star_planning` returns three empty tuples when no route found, despite returns Path class when ok.
This mismatch causes the crash of subsequent plot function.
Example: Surround the vehicle with walls
```diff
@@ -382,16 +382,16 @@ def main():
ox, oy = [], []
-    for i in range(60):
+    for i in range(15):
ox.append(i) …
```
=> fix: Hybrid A* behavior when path is not found

PathPlanning/AStar/a_star_searching_from_two_side.py
Improve Performance #1074  
https://github.com/AtsushiSakai/PythonRobotics/blob/ad600cd9023e67cd8064b678213d6586d076dd15/PathPlanning/AStar/a_star_searching_from_two_side.py#L80C1-L117C20  
In the referenced function, the search for coordinates and neighbors in `ob_list` and `neighbors` occurs frequently, especially for long obstacles. This change optimizes the process by storing obstacles and neighbors in a set. Sets use a hashmap for lookups, significantly improving efficiency compared to linear search. This modification aims to enhance performance in scenarios with long obstacle lists by reducing the time complexity of lookups
=>  Hashmap instead of a linear search issue number is #1074  

PathPlanning/BreadthFirstSearch/breadth_first_search.py, PathPlanning/Dijkstra/dijkstra.py, PathPlanning/ProbabilisticRoadMap/probabilistic_road_map.py, PathPlanning/VoronoiRoadMap/voronoi_road_map.py, requirements/requirements.txt
This PR ensures that the lists provided to some path planning algorithms are all `int`s and not a mix of `float` and `int`.
=> Fixed multitype list

ArmNavigation/arm_obstacle_navigation/arm_obstacle_navigation.py, ArmNavigation/arm_obstacle_navigation/arm_obstacle_navigation_2.py, PathPlanning/DynamicMovementPrimitives/dynamic_movement_primitives.py, PathPlanning/Eta3SplineTrajectory/eta3_spline_trajectory.py, PathPlanning/RRT/sobol/sobol.py
=> Fix lint error

docs/getting_started_main.rst, docs/modules/path_planning/catmull_rom_spline/catmull_rom_spline_main.rst
=> Fix Doc generation warning

docs/modules/0_getting_started/0_getting_started_main.rst, docs/modules/0_getting_started/1_what_is_python_robotics_main.rst, docs/modules/0_getting_started/2_how_to_run_sample_codes_main.rst
=> update getting started

docs/modules/0_getting_started/3_how_to_contribute_main.rst, docs/modules/1_introduction/2_python_for_robotics/python_for_robotics_main.rst
=> update introduction doc

docs/modules/1_introduction/2_python_for_robotics/python_for_robotics_main.rst
=> update introduction doc for python

docs/modules/12_appendix/appendix_main.rst, docs/modules/12_appendix/external_sensors_main.rst
=> add external sensors documentation to appendix

docs/modules/12_appendix/external_sensors_main.rst, docs/modules/12_appendix/internal_sensors_main.rst, docs/modules/1_introduction/1_definition_of_robotics/definition_of_robotics_main.rst, docs/modules/1_introduction/3_technologies_for_robotics/technologies_for_robotics_main.rst, docs/modules/1_introduction/introduction_main.rst
=> fix: update robotics documentation for clarity and correct terminology

Control/move_to_pose/move_to_pose.py, tests/test_move_to_pose.py
fix #877
- Update move_to_pose for cases where alpha > pi/2 or alpha < -pi/2
- Format move_to_pose.py using Ruff
Current results:
Previous results(master):
=> Update move_to_pose for cases where alpha > pi/2 or alpha < -pi/2

docs/conf.py
=> feat: add linkcode_resolve function for enhanced documentation linking

PathTracking/lqr_speed_steer_control/lqr_speed_steer_control.py, PathTracking/lqr_steer_control/lqr_steer_control.py, PathTracking/rear_wheel_feedback/rear_wheel_feedback.py, PathTracking/stanley_controller/stanley_controller.py
fix "ModuleNotFoundError: No module named 'utils'" when running certain algorithom .py file in PathTracking
=> fix "ModuleNotFoundError: No module named 'utils'"

AerialNavigation/rocket_powered_landing/rocket_powered_landing.py, InvertedPendulum/inverted_pendulum_mpc_control.py, requirements/requirements.txt, tests/conftest.py
=> build(deps): update cvxpy version from 1.5.3 to 1.6.5 in requirements

Mapping/circle_fitting/circle_fitting.py, Mapping/kmeans_clustering/kmeans_clustering.py, Mapping/ray_casting_grid_map/ray_casting_grid_map.py, docs/modules/3_mapping/circle_fitting/circle_fitting_main.rst, docs/modules/3_mapping/distance_map/distance_map_main.rst, docs/modules/3_mapping/gaussian_grid_map/gaussian_grid_map_main.rst, docs/modules/3_mapping/k_means_object_clustering/k_means_object_clustering_main.rst, docs/modules/3_mapping/lidar_to_grid_map_tutorial/lidar_to_grid_map_tutorial_main.rst, docs/modules/3_mapping/normal_vector_estimation/normal_vector_estimation_main.rst, docs/modules/3_mapping/point_cloud_sampling/point_cloud_sampling_main.rst, docs/modules/3_mapping/ray_casting_grid_map/ray_casting_grid_map_main.rst, docs/modules/3_mapping/rectangle_fitting/rectangle_fitting_main.rst, tests/test_ray_casting_grid_map.py, tests/test_raycasting_grid_map.py
Updated documentation to rename "API" sections to "Code Link" for clarity and consistency. Enhanced docstrings for `circle_fitting` and `kmeans_clustering` functions, improving parameter descriptions and adding return value details. Fixed typos in function and file names in the ray casting grid map module.
=> Refactor module links and improve code documentation.

docs/modules/12_appendix/internal_sensors_main.rst
This pull request rewrites and enhances the "Internal Sensors for Robots" section in the appendix.
- Reformatted the content to match the structure and tone of the "External Sensors for Robots" section
- Added detailed descriptions for each sensor: GNSS, Gyroscope, Accelerometer, Magnetometer, IMU, Pressure Sensor, and Temperature Sensor
- Unified the content into clear, single-paragraph summaries per sensor
- Included properly formatted references in reStructuredText (RST) format for consistency with Sphinx and ReadTheDocs
Closes #1162
=> docs: rewrite internal sensors section with detailed descriptions and references

.github/pull_request_template.md, README.md, users_comments.md
Fix broken links to GitHub pages and GIF files.
=> Fix broken links to GitHub pages and GIF files.

PathPlanning/StateLatticePlanner/state_lattice_planner.py
Couldn't run lattice_planner.py because it was giving module not found error.
It adds the root of the directory to the sys.path so that eliminates the module not found error.
=> Add root directory to system path for lattice planner

PathTracking/pure_pursuit/pure_pursuit.py, tests/test_pure_pursuit.py
1. add reverse mode in pure pursuit and unit test
2. add visualization of vehicle
=> feat: Add reverse mode in pure pursuit

PathPlanning/DStarLite/d_star_lite.py
resolves #817 
Building on #817, this PR improves both performance and readability by using sets for obstacle management in `DStarLite`.
This change reduces the computational complexity of `is_obstacle` from O(n) to O(1) average with respect to the number of obstacles. On my local environment, test execution time was improved from 1.72 seconds to 0.82 seconds.
While the suggested improvement in the original issue used dictionaries, I opted for sets to achieve both greater efficiency and more concise code.
=> Improve speed and readability of is_obstacle in DStarLite

docs/modules/12_appendix/external_sensors_main.rst
fix issue #1160: https://github.com/AtsushiSakai/PythonRobotics/issues/1160
Adds basic information about some external sensors which were "TBD" in the document.
=> Enhance external sensors documentation. 

PathTracking/model_predictive_speed_and_steer_control/model_predictive_speed_and_steer_control.py
This PR fixes the scope of range function as described in issue #1263
=> fixed the scope of range function
